subcurrency.type(1);
subcurrency.to("BNEz2wgeaARdPQT049sQOY8Ceox6NjdchBi02F2n4cRGLZg8qbz5lN9d20XpWOWk5pe358+40cmqWSHl9wLna/g=");
subcurrency.amount(1);
subcurrency.contract_id("smNS5nh9+rYThL095bt6oQIi6jQYbL2FZtleyxxroyM=")
subcurrency_balance.value("smNS5nh9+rYThL095bt6oQIi6jQYbL2FZtleyxxroyM=");
binary_interface_offer.amount1("100");
binary_interface_offer.amount2("100");
binary_interface_offer.timelimit("2");
binary_interface_offer.oracle_start_height("10");
binary_interface_offer.oracle_text("1=1");
binary_interface_offer.direction("true");
